name: Auto tag

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomli

      - name: Extract version
        id: extract_version
        run: |
          version=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['tool']['poetry']['version'])")
          echo "version=$version" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git rev-parse "v$version" >/dev/null 2>&1; then
            echo "Tag v$version already exists."
            exit 0
          fi

          git tag "v$version"
          git push origin "v$version"
