name: CD

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry, cyclonedx-bom
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          sudo pipx ensurepath --global
          pipx install poetry cyclonedx-bom

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
        working-directory: ${{ github.workspace }}

      - name: Build wheel
        run: |
          poetry build
        working-directory: ${{ github.workspace }}

      - name: Generate SBOM
        run: |
          cyclonedx-py poetry > cyclonedx-sbom.json
        working-directory: ${{ github.workspace }}

      - name: Attest
        id: attest
        uses: actions/attest-sbom@v1.4.1
        with:
          subject-path: '${{ github.workspace }}/dist/*.whl'
          sbom-path: '${{ github.workspace }}/cyclonedx-sbom.json'
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            cyclonedx-sbom.json
            ${{ steps.attest.outputs.bundle-path }}
