name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-validate-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          sudo pipx ensurepath --global
          pipx install poetry

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Run ruff
        run: |
          poetry run ruff check .
        working-directory: ${{ github.workspace }}

      - name: Run pylint
        run: |
          poetry run pylint --ignore=tests .
        working-directory: ${{ github.workspace }}

      - name: Run bandit
        run: |
          poetry run bandit -r . -x ./tests
        working-directory: ${{ github.workspace }}

      - name: Run trufflehog
        run: |
          poetry run trufflehog filesystem .
        working-directory: ${{ github.workspace }}

      - name: Run pytest
        run: |
          PYTHONPATH=. poetry run pytest
        working-directory: ${{ github.workspace }}
